version: "3.8"

services:
  postgres_db:
    container_name: ${POSTGRES_HOST}
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:

networks:
  server_network: